name: Build and Upload Artifact

on:
  release:
    types: [created]

jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Get release tag
        id: get_release_tag
        run: echo "::set-output name=tag::$(jq -r .release.tag_name ${GITHUB_EVENT_PATH})"

      - name: Get release URL
        id: get_release_url
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Zip dist folder
        run: zip -r "${{ steps.get_release_tag.outputs.tag }}.zip" dist

      - name: Attach artifact to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_url.outputs.upload_url }}
          asset_path: "${{ steps.get_release_tag.outputs.tag }}.zip"
          asset_name: "${{ steps.get_release_tag.outputs.tag }}.zip"
          asset_content_type: application/zip
